"""
Analysis 2: Per-field evaluation — breakdown accuracy by field.
Reads the predictions generated by analysis_1 and computes per-field metrics.

Usage:
    python scripts/analysis_2_per_field.py
"""
import json
import sys
from pathlib import Path
from collections import defaultdict

from sklearn.metrics import accuracy_score, f1_score, matthews_corrcoef, precision_score, recall_score

def main():
    pred_path = Path("/mnt/nvme1/lcx/academic_social_impact/analysis/test_predictions_with_explanations.json")
    with open(pred_path) as f:
        data = json.load(f)

    # Overall
    labels = [d["true_label"] for d in data]
    preds = [d["predicted"] for d in data]
    print(f"Overall: Acc={accuracy_score(labels, preds):.4f} F1={f1_score(labels, preds):.4f} MCC={matthews_corrcoef(labels, preds):.4f}")
    print(f"Total: {len(data)}\n")

    # Per field
    field_data = defaultdict(lambda: {"labels": [], "preds": []})
    for d in data:
        field = d.get("field", "Unknown")
        field_data[field]["labels"].append(d["true_label"])
        field_data[field]["preds"].append(d["predicted"])

    print(f"{'Field':<50s} {'N':>6s} {'Acc':>7s} {'Prec':>7s} {'Rec':>7s} {'F1':>7s} {'MCC':>7s}")
    print("-" * 92)

    results = []
    for field in sorted(field_data.keys(), key=lambda x: -len(field_data[x]["labels"])):
        fd = field_data[field]
        n = len(fd["labels"])
        if n < 50:
            continue
        acc = accuracy_score(fd["labels"], fd["preds"])
        prec = precision_score(fd["labels"], fd["preds"], zero_division=0)
        rec = recall_score(fd["labels"], fd["preds"], zero_division=0)
        f1 = f1_score(fd["labels"], fd["preds"], zero_division=0)
        mcc = matthews_corrcoef(fd["labels"], fd["preds"])
        print(f"  {field:<48s} {n:>6d} {acc:>7.4f} {prec:>7.4f} {rec:>7.4f} {f1:>7.4f} {mcc:>7.4f}")
        results.append({"field": field, "n": n, "acc": round(acc,4), "prec": round(prec,4),
                        "rec": round(rec,4), "f1": round(f1,4), "mcc": round(mcc,4)})

    out_path = Path("/mnt/nvme1/lcx/academic_social_impact/analysis/per_field_metrics.json")
    with open(out_path, "w") as f:
        json.dump(results, f, indent=2)
    print(f"\nSaved to {out_path}")


if __name__ == "__main__":
    main()
